// ========== TODOS OS FEITIÇOS DAS 4 CLASSES RESTANTES ==========
// Caçador, Guardião, Clérigo, Berserker (26 × 4 = 104 feitiços)
// RECALIBRADO para HP base 50

const DB_FEITICOS_TODAS_CLASSES = {
    // === CAÇADOR (21) ===
    cacador: [
        // Água (5)
        {id:'cacador_garra_aquatica',catalogId:'0703000001',name:'Garra Aquática',icon:'🐺',class:'cacador',element:'water',spellType:'active',castType:'targeted',targetType:'enemy',paCost:3,minRange:1,maxRange:2,rangeShape:'cross',aoeType:'single',damage:{min:6,max:10,stat:'luck'},zoneEffects:{lifeSteal:true},onKill:{enabled:true,effects:[{type:'stealHP',percent:15}]},description:'Life steal. Rouba 15% HP ao matar.'},
        {id:'cacador_cura_torrencial',catalogId:'0703000002',name:'Cura Torrencial',icon:'💧',class:'cacador',element:'water',spellType:'active',castType:'self',targetType:'none',paCost:3,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'single',heal:{min:10,max:16,stat:'wisdom'},cooldown:3,description:'Auto-cura 10-16.'},
        {id:'cacador_prisao_agua',catalogId:'0703000003',name:'Prisão de Água',icon:'🔒',class:'cacador',element:'water',spellType:'active',castType:'targeted',targetType:'enemy',paCost:4,minRange:2,maxRange:4,rangeShape:'cross',aoeType:'single',damage:{min:5,max:9,stat:'luck'},advancedStatus:[{type:'preso',duration:1}],cooldown:3,description:'Prende 1 turno.'},
        {id:'cacador_vortice_draconiano',catalogId:'0703000004',name:'Vórtice Draconiano',icon:'🌊',class:'cacador',element:'water',spellType:'active',castType:'targeted',targetType:'enemy',paCost:5,peCost:1,minRange:2,maxRange:5,rangeShape:'circle',aoeType:'zone',zoneCells:[{dx:0,dy:0},{dx:-1,dy:0},{dx:1,dy:0},{dx:0,dy:-1},{dx:0,dy:1}],zoneEffects:{dmgEnemy:true,lifeSteal:false},damage:{min:10,max:16,stat:'luck'},pushPull:{type:'pull',distance:2,origin:'zone_center'},cooldown:4,description:'Puxa inimigos + dano.'},
        {id:'cacador_maremoto_furia',catalogId:'0703000005',name:'Maremoto de Fúria',icon:'🌊',class:'cacador',element:'water',spellType:'active',castType:'targeted',targetType:'enemy',paCost:6,peCost:2,minRange:2,maxRange:6,rangeShape:'line',aoeType:'zone',zoneCells:[{dx:-1,dy:0},{dx:0,dy:0},{dx:1,dy:0},{dx:-1,dy:1},{dx:0,dy:1},{dx:1,dy:1}],zoneEffects:{dmgEnemy:true,lifeSteal:true},damage:{min:14,max:22,stat:'luck'},cooldown:5,description:'Maremoto com life steal.'},
        // Ar (5)
        {id:'cacador_garras_vento',catalogId:'0703000006',name:'Garras de Vento',icon:'💨',class:'cacador',element:'air',spellType:'active',castType:'targeted',targetType:'enemy',paCost:3,minRange:1,maxRange:3,rangeShape:'circle',aoeType:'single',damage:{min:7,max:11,stat:'agility'},onKill:{enabled:true,effects:[{type:'stealPM',amount:1},{type:'stealShield',amount:5}]},description:'Rouba PM e escudo ao matar.'},
        {id:'cacador_corrente_ascendente',catalogId:'0703000007',name:'Corrente Ascendente',icon:'⬆️',class:'cacador',element:'air',spellType:'active',castType:'targeted',targetType:'both',paCost:4,minRange:2,maxRange:6,rangeShape:'cross',aoeType:'single',effect:'swapPosition',checkEstabilizado:true,damage:{min:10,max:16,stat:'agility'},cooldown:3,description:'Troca posição + dano.'},
        {id:'cacador_ciclone_draconiano',catalogId:'0703000008',name:'Ciclone Draconiano',icon:'🌪️',class:'cacador',element:'air',spellType:'active',castType:'self',targetType:'enemy',paCost:5,peCost:1,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'zone',zoneCells:[{dx:-2,dy:0},{dx:-1,dy:-1},{dx:-1,dy:0},{dx:-1,dy:1},{dx:0,dy:-2},{dx:0,dy:-1},{dx:0,dy:0},{dx:0,dy:1},{dx:0,dy:2},{dx:1,dy:-1},{dx:1,dy:0},{dx:1,dy:1},{dx:2,dy:0}],zoneEffects:{dmgEnemy:true},damage:{min:8,max:14,stat:'agility'},pushPull:{type:'pull',distance:3,origin:'caster'},advancedStatus:[{type:'ensaboado',duration:2}],cooldown:4,description:'Puxa todos + ensaboado.'},
        {id:'cacador_danca_ventos',catalogId:'0703000009',name:'Dança dos Ventos',icon:'🌀',class:'cacador',element:'air',spellType:'active',castType:'self',targetType:'none',paCost:3,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'single',advancedStatus:[{type:'ensaboado',duration:3}],effects:[{effectId:'poderoso',level:1,target:'self'}],cooldown:4,description:'Ensaboado + dano por 2 turnos.'},
        {id:'cacador_furacao_selvagem',catalogId:'0703000010',name:'Furacão Selvagem',icon:'🌪️',class:'cacador',element:'air',spellType:'active',castType:'self',targetType:'enemy',paCost:6,peCost:2,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'zone',zoneCells:[{dx:-2,dy:-2},{dx:-1,dy:-2},{dx:0,dy:-2},{dx:1,dy:-2},{dx:2,dy:-2},{dx:-2,dy:-1},{dx:-1,dy:-1},{dx:0,dy:-1},{dx:1,dy:-1},{dx:2,dy:-1},{dx:-2,dy:0},{dx:-1,dy:0},{dx:0,dy:0},{dx:1,dy:0},{dx:2,dy:0},{dx:-2,dy:1},{dx:-1,dy:1},{dx:0,dy:1},{dx:1,dy:1},{dx:2,dy:1},{dx:-2,dy:2},{dx:-1,dy:2},{dx:0,dy:2},{dx:1,dy:2},{dx:2,dy:2}],zoneEffects:{dmgEnemy:true},damage:{min:10,max:18,stat:'agility'},cooldown:5,description:'Furacão massivo 5x5.'},
        // Terra (5)
        {id:'cacador_impacto_draconiano',catalogId:'0703000011',name:'Impacto Draconiano',icon:'🐲',class:'cacador',element:'earth',spellType:'active',castType:'targeted',targetType:'enemy',paCost:4,minRange:1,maxRange:2,rangeShape:'cross',aoeType:'single',damage:{min:10,max:16,stat:'strength'},armorSteal:{flat:8},description:'Rouba 8 de escudo.'},
        {id:'cacador_prisao_rochosa',catalogId:'0703000012',name:'Prisão Rochosa',icon:'🪨',class:'cacador',element:'earth',spellType:'active',castType:'targeted',targetType:'enemy',paCost:4,minRange:2,maxRange:4,rangeShape:'cross',aoeType:'single',damage:{min:6,max:10,stat:'strength'},advancedStatus:[{type:'preso',duration:2}],cooldown:4,description:'Prende 2 turnos.'},
        {id:'cacador_pele_escamas',catalogId:'0703000013',name:'Pele de Escamas',icon:'🐉',class:'cacador',element:'earth',spellType:'active',castType:'self',targetType:'none',paCost:3,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'single',armorGrant:{min:10,max:16},onHitTaken:{enabled:true,minDamage:8,effects:[{type:'shield',amount:5,duration:1}]},cooldown:3,description:'Escudo + ganha 5 ao sofrer 8+ dmg.'},
        {id:'cacador_terremoto_ancestral',catalogId:'0703000014',name:'Terremoto Ancestral',icon:'🌍',class:'cacador',element:'earth',spellType:'active',castType:'self',targetType:'enemy',paCost:5,peCost:1,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'zone',zoneCells:[{dx:-2,dy:0},{dx:-1,dy:-1},{dx:-1,dy:0},{dx:-1,dy:1},{dx:0,dy:-2},{dx:0,dy:-1},{dx:0,dy:0},{dx:0,dy:1},{dx:0,dy:2},{dx:1,dy:-1},{dx:1,dy:0},{dx:1,dy:1},{dx:2,dy:0}],zoneEffects:{dmgEnemy:true},damage:{min:10,max:16,stat:'strength'},cooldown:4,description:'Terremoto em área grande.'},
        {id:'cacador_furia_terrestre',catalogId:'0703000015',name:'Fúria Terrestre',icon:'🌍',class:'cacador',element:'earth',spellType:'active',castType:'targeted',targetType:'enemy',paCost:6,peCost:2,minRange:1,maxRange:3,rangeShape:'circle',aoeType:'single',damage:{min:22,max:32,stat:'strength'},damageScaling:{type:'execute',threshold:30,bonus:30},onKill:{enabled:true,effects:[{type:'stealHP',percent:30},{type:'stealArmor',amount:10}]},cooldown:5,description:'+30% dano se o alvo tiver ≤30% vida (Execute). Rouba HP e escudo ao matar.'},
        // Ativos (3)
        {id:'cacador_evasao',catalogId:'0703000016',name:'Evasão',icon:'💨',class:'cacador',element:'none',spellType:'active',castType:'targeted',targetType:'none',paCost:3,minRange:2,maxRange:4,rangeShape:'circle',aoeType:'single',effect:'teleport',advancedStatus:[{type:'ensaboado',duration:1}],cooldown:3,description:'Teleporte + ensaboado 1 turno.'},
        {id:'cacador_troca_tatica',catalogId:'0703000017',name:'Troca Tática',icon:'🔄',class:'cacador',element:'none',spellType:'active',castType:'targeted',targetType:'both',paCost:4,minRange:2,maxRange:6,rangeShape:'circle',aoeType:'single',effect:'swapPosition',checkEstabilizado:true,heal:{min:10,max:16,stat:'wisdom'},cooldown:4,description:'Troca posição. Cura 10-16 se aliado.'},
        {id:'cacador_corrente_ascendente_pos',catalogId:'0703000018',name:'Corrente Ascendente',icon:'⬆️',class:'cacador',element:'none',spellType:'active',castType:'targeted',targetType:'enemy',paCost:5,minRange:2,maxRange:4,rangeShape:'cross',aoeType:'single',effect:'swapPosition',checkEstabilizado:true,damage:{min:16,max:22,stat:'agility'},cooldown:4,description:'Troca posição + dano.'},
        // Ativos extras (2)
        {id:'cacador_emboscada',catalogId:'0703000022',name:'Emboscada',icon:'🗡️',class:'cacador',element:'none',spellType:'active',castType:'targeted',targetType:'enemy',paCost:3,minRange:2,maxRange:5,rangeShape:'circle',aoeType:'single',effect:'teleportBehind',damage:{min:8,max:14,stat:'agility'},cooldown:3,description:'Teleporta atrás do inimigo + dano.'},
        {id:'cacador_rugido_feroz',catalogId:'0703000023',name:'Rugido Feroz',icon:'🦁',class:'cacador',element:'none',spellType:'active',castType:'self',targetType:'enemy',paCost:2,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'zone',zoneCells:[{dx:-1,dy:-1},{dx:0,dy:-1},{dx:1,dy:-1},{dx:-1,dy:0},{dx:0,dy:0},{dx:1,dy:0},{dx:-1,dy:1},{dx:0,dy:1},{dx:1,dy:1}],zoneEffects:{dmgEnemy:false},pushPull:{type:'push',distance:1,origin:'caster'},cooldown:3,description:'Empurra todos inimigos adjacentes 1 célula.'},
        // Passivos (5)
        {id:'cacador_passivo_instinto_predador',catalogId:'0703000019',name:'Instinto Predador',icon:'🐺',class:'cacador',element:'none',spellType:'passive',castType:'self',targetType:'none',passiveEffect:{onKill:{enabled:true,firstKillPerTurn:true,effects:[{type:'stealHP',percent:20,useLastHitDamage:true},{type:'stealPM',amount:1}]}},description:'Ao matar o 1º inimigo por turno: rouba 20% do dano do golpe final como HP e 1 PM.'},
        {id:'cacador_passivo_regeneracao',catalogId:'0703000020',name:'Regeneração Dracônica',icon:'💚',class:'cacador',element:'none',spellType:'passive',castType:'self',targetType:'none',passiveEffect:{onTurnStart:{enabled:true,effects:[{type:'heal',percent:5}]}},description:'Regenera 5% HP por turno.'},
        // Passivos extras (3)
        {id:'cacador_passivo_instinto_selvagem',catalogId:'0703000024',name:'Instinto Selvagem',icon:'🐾',class:'cacador',element:'none',spellType:'passive',castType:'self',targetType:'none',passiveEffect:{combatStartPM:1},description:'+1 PM no início do combate.'},
        {id:'cacador_passivo_caca_fraco',catalogId:'0703000025',name:'Caça ao Fraco',icon:'🎯',class:'cacador',element:'none',spellType:'passive',castType:'self',targetType:'none',passiveEffect:{executeDamageBonus:{hpThreshold:30,damagePercent:20}},description:'+20% dano contra alvos abaixo de 30% HP.'},
        {id:'cacador_passivo_espirito_natureza',catalogId:'0703000026',name:'Espírito da Natureza',icon:'🌿',class:'cacador',element:'none',spellType:'passive',castType:'self',targetType:'none',passiveEffect:{allResistance:5},description:'+5 resistência a todos os elementos.'},
        // DOM (1)
        {id:'cacador_dom_forma_draconica',catalogId:'0703000021',name:'DOM: Forma Dracônica',icon:'🐲',class:'cacador',element:'none',spellType:'active',castType:'self',targetType:'none',paCost:0,peCost:3,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'single',effects:[{effectId:'poderoso',level:3,target:'self'},{effectId:'cura_amplificada',level:3,target:'self'}],armorGrant:{min:16,max:25},advancedStatus:[{type:'ensaboado',duration:3}],cooldown:6,description:'Forma dracônica: +20% dmg, +30% cura, 16-25 escudo, ensaboado 3 turnos.'}
    ],

    // === GUARDIÃO (21) ===
    guardiao: [
        // Terra (5)
        {id:'guardiao_muralha_guardian',catalogId:'0704000001',name:'Muralha do Guardião',icon:'🧱',class:'guardiao',element:'earth',spellType:'active',castType:'self',targetType:'none',paCost:3,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'single',armorGrant:{min:10,max:16},onBlock:{enabled:true,minDamageBlocked:8,effects:[{type:'armor',amount:5,duration:1}]},description:'Escudo. Ao bloquear 8+, ganha mais 5.'},
        {id:'guardiao_bastiao',catalogId:'0704000002',name:'Bastião',icon:'🛡️',class:'guardiao',element:'earth',spellType:'active',castType:'self',targetType:'none',paCost:4,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'single',advancedStatus:[{type:'estabilizado',duration:2}],armorGrant:{min:12,max:18},cooldown:4,description:'Estabilizado + escudo por 2 turnos.'},
        {id:'guardiao_fortificacao',catalogId:'0704000003',name:'Fortificação',icon:'🏰',class:'guardiao',element:'earth',spellType:'active',castType:'self',targetType:'none',paCost:3,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'single',effects:[{effectId:'escudo_recebido',level:2,target:'self'}],cooldown:3,description:'+30% escudo recebido por 2 turnos.'},
        {id:'guardiao_aegis_rochosa',catalogId:'0704000004',name:'Aegis Rochosa',icon:'🛡️',class:'guardiao',element:'earth',spellType:'active',castType:'targeted',targetType:'ally',paCost:4,minRange:1,maxRange:4,rangeShape:'cross',aoeType:'single',armorGrant:{min:14,max:20},cooldown:3,description:'Concede 14-20 escudo para aliado.'},
        {id:'guardiao_fortaleza_inabalavel',catalogId:'0704000005',name:'Fortaleza Inabalável',icon:'🏰',class:'guardiao',element:'earth',spellType:'active',castType:'self',targetType:'none',paCost:5,peCost:1,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'single',advancedStatus:[{type:'estabilizado',duration:3}],armorGrant:{min:18,max:25},cooldown:5,description:'Estabilizado + 18-25 escudo por 3 turnos.'},
        // Fogo (5)
        {id:'guardiao_escudo_chamas',catalogId:'0704000006',name:'Escudo de Chamas',icon:'🔥',class:'guardiao',element:'fire',spellType:'active',castType:'self',targetType:'none',paCost:3,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'single',armorGrant:{min:8,max:14},onHitTaken:{enabled:true,minDamage:6,effects:[{type:'reflectDamage',percent:30}]},cooldown:3,description:'Escudo. Reflete 30% dmg sofrido.'},
        {id:'guardiao_retaliacao_ardente',catalogId:'0704000007',name:'Retaliação Ardente',icon:'🔥',class:'guardiao',element:'fire',spellType:'active',castType:'targeted',targetType:'enemy',paCost:4,minRange:1,maxRange:2,rangeShape:'cross',aoeType:'single',damage:{min:10,max:16,stat:'strength'},bonusVsArmored:50,onBlock:{enabled:true,minDamageBlocked:8,effects:[{type:'damageBonus',percent:20,duration:2}]},description:'+50% vs escudo. Ao bloquear, +20% dmg.'},
        {id:'guardiao_barreira_fogo',catalogId:'0704000008',name:'Barreira de Fogo',icon:'🧱',class:'guardiao',element:'fire',spellType:'active',castType:'self',targetType:'enemy',paCost:5,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'zone',zoneCells:[{dx:-1,dy:-1},{dx:0,dy:-1},{dx:1,dy:-1},{dx:-1,dy:0},{dx:1,dy:0},{dx:-1,dy:1},{dx:0,dy:1},{dx:1,dy:1}],zoneEffects:{dmgEnemy:true},damage:{min:6,max:10,stat:'intelligence'},armorGrant:{min:8,max:14},cooldown:3,description:'Barreira ao redor + dano.'},
        {id:'guardiao_ira_justa',catalogId:'0704000009',name:'Ira Justa',icon:'⚖️',class:'guardiao',element:'fire',spellType:'active',castType:'targeted',targetType:'enemy',paCost:4,minRange:1,maxRange:3,rangeShape:'cross',aoeType:'single',damage:{min:11,max:16,stat:'intelligence'},damageScaling:{type:'berserk',threshold:50,bonus:30},description:'+30% dano se você tiver 50% de vida ou menos (Berserk).'},
        {id:'guardiao_imolacao_protetora',catalogId:'0704000010',name:'Imolação Protetora',icon:'💀',class:'guardiao',element:'fire',spellType:'active',castType:'self',targetType:'enemy',paCost:6,peCost:2,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'zone',zoneCells:[{dx:-2,dy:0},{dx:-1,dy:-1},{dx:-1,dy:0},{dx:-1,dy:1},{dx:0,dy:-2},{dx:0,dy:-1},{dx:0,dy:0},{dx:0,dy:1},{dx:0,dy:2},{dx:1,dy:-1},{dx:1,dy:0},{dx:1,dy:1},{dx:2,dy:0}],zoneEffects:{dmgEnemy:true},damage:{min:14,max:22,stat:'intelligence'},selfDamage:{type:'percent',amount:10},armorGrant:{min:16,max:25},cooldown:5,description:'Explosão + escudo. Auto-dano 10%.'},
        // Água (5)
        {id:'guardiao_escudo_luz',catalogId:'0704000011',name:'Escudo de Luz',icon:'✨',class:'guardiao',element:'water',spellType:'active',castType:'targeted',targetType:'ally',paCost:3,minRange:1,maxRange:5,rangeShape:'cross',aoeType:'single',armorGrant:{min:12,max:18},description:'Concede 12-18 escudo.'},
        {id:'guardiao_cura_protetora',catalogId:'0704000012',name:'Cura Protetora',icon:'💧',class:'guardiao',element:'water',spellType:'active',castType:'targeted',targetType:'ally',paCost:4,minRange:1,maxRange:4,rangeShape:'cross',aoeType:'single',heal:{min:10,max:16,stat:'wisdom'},armorGrant:{min:6,max:10},cooldown:3,description:'Cura + escudo.'},
        {id:'guardiao_resgate_heroico',catalogId:'0704000013',name:'Resgate Heroico',icon:'🛡️',class:'guardiao',element:'water',spellType:'active',castType:'targeted',targetType:'ally',paCost:4,minRange:2,maxRange:6,rangeShape:'circle',aoeType:'single',effect:'swapPosition',armorGrant:{min:8,max:14},cooldown:4,description:'Troca com aliado + 8-14 escudo.'},
        {id:'guardiao_refluxo_protetor',catalogId:'0704000014',name:'Refluxo Protetor',icon:'💧',class:'guardiao',element:'water',spellType:'active',castType:'self',targetType:'none',paCost:3,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'single',heal:{min:8,max:14,stat:'wisdom'},armorGrant:{min:6,max:10},cooldown:3,description:'Auto-cura + escudo.'},
        {id:'guardiao_santuario_aquatico',catalogId:'0704000015',name:'Santuário Aquático',icon:'💧',class:'guardiao',element:'water',spellType:'active',castType:'self',targetType:'ally',paCost:6,peCost:2,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'zone',zoneCells:[{dx:-1,dy:-1},{dx:0,dy:-1},{dx:1,dy:-1},{dx:-1,dy:0},{dx:0,dy:0},{dx:1,dy:0},{dx:-1,dy:1},{dx:0,dy:1},{dx:1,dy:1}],zoneEffects:{healCaster:true,healAlly:true},heal:{min:12,max:18,stat:'wisdom'},armorGrant:{min:12,max:18},cooldown:5,description:'Cura + escudo em área 3x3 (aliados).'},
        // Ativos (3)
        {id:'guardiao_provocar',catalogId:'0704000016',name:'Provocar',icon:'😠',class:'guardiao',element:'none',spellType:'active',castType:'targeted',targetType:'enemy',paCost:2,minRange:1,maxRange:5,rangeShape:'cross',aoeType:'single',effect:'taunt',duration:2,cooldown:3,description:'Força inimigo a atacar você por 2 turnos.'},
        {id:'guardiao_bastiao_ativo',catalogId:'0704000017',name:'Bastião Ativo',icon:'🛡️',class:'guardiao',element:'none',spellType:'active',castType:'self',targetType:'none',paCost:4,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'single',advancedStatus:[{type:'estabilizado',duration:2}],armorGrant:{min:12,max:18},cooldown:4,description:'Estabilizado + escudo.'},
        {id:'guardiao_aegis',catalogId:'0704000018',name:'Aegis',icon:'🛡️',class:'guardiao',element:'none',spellType:'active',castType:'self',targetType:'none',paCost:3,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'single',effects:[{effectId:'escudo_recebido',level:2,target:'self'}],cooldown:3,description:'+30% escudo recebido.'},
        // Ativos extras (2)
        {id:'guardiao_escudo_divino',catalogId:'0704000022',name:'Escudo Divino',icon:'✨',class:'guardiao',element:'none',spellType:'active',castType:'targeted',targetType:'ally',paCost:3,minRange:1,maxRange:5,rangeShape:'cross',aoeType:'single',effect:'redirectDamage',redirectPercent:50,duration:2,cooldown:4,description:'Redireciona 50% do dano de um aliado para você por 2 turnos.'},
        {id:'guardiao_sacrificio',catalogId:'0704000023',name:'Sacrifício',icon:'❤️',class:'guardiao',element:'none',spellType:'active',castType:'targeted',targetType:'ally',paCost:4,minRange:1,maxRange:4,rangeShape:'cross',aoeType:'single',heal:{min:12,max:18,stat:'wisdom'},selfDamage:{type:'flat',amount:8},cooldown:3,description:'Cura aliado 12-18 HP. Perde 8 HP.'},
        // Passivos (5)
        {id:'guardiao_passivo_guardiao_eterno',catalogId:'0704000019',name:'Guardião Eterno',icon:'♾️',class:'guardiao',element:'none',spellType:'passive',castType:'self',targetType:'none',passiveEffect:{onHitTaken:{enabled:true,minDamage:8,effects:[{type:'armor',amount:6,duration:2}]},onBlock:{enabled:true,minDamageBlocked:8,effects:[{type:'armor',amount:8,duration:2}]}},description:'Ao sofrer 8+ ou bloquear 8+, ganha escudo.'},
        {id:'guardiao_passivo_escudo_vivo',catalogId:'0704000020',name:'Escudo Vivo',icon:'🛡️',class:'guardiao',element:'none',spellType:'passive',castType:'self',targetType:'none',passiveEffect:{armor_received:20,maxHpPercent:15},description:'+20% escudo recebido, +15% HP máx.'},
        // Passivos extras (3)
        {id:'guardiao_passivo_vigilancia',catalogId:'0704000024',name:'Vigilância Eterna',icon:'👁️',class:'guardiao',element:'none',spellType:'passive',castType:'self',targetType:'none',passiveEffect:{block:10},description:'+10% bloqueio.'},
        {id:'guardiao_passivo_aura_protetora',catalogId:'0704000025',name:'Aura Protetora',icon:'💫',class:'guardiao',element:'none',spellType:'passive',castType:'self',targetType:'none',passiveEffect:{allyAdjacentArmor:{amount:4,onTurnStart:true}},description:'Aliados adjacentes ganham 4 de escudo no início do seu turno.'},
        {id:'guardiao_passivo_resistencia_natural',catalogId:'0704000026',name:'Resistência Natural',icon:'🏔️',class:'guardiao',element:'none',spellType:'passive',castType:'self',targetType:'none',passiveEffect:{allResistance:8},description:'+8 resistência a todos os elementos.'},
        // DOM (1)
        {id:'guardiao_dom_fortaleza_absoluta',catalogId:'0704000021',name:'DOM: Fortaleza Absoluta',icon:'🏰',class:'guardiao',element:'none',spellType:'active',castType:'self',targetType:'none',paCost:0,peCost:3,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'single',advancedStatus:[{type:'estabilizado',duration:4}],armorGrant:{min:25,max:35},effects:[{effectId:'escudo_recebido',level:3,target:'self'}],onBlock:{enabled:true,minDamageBlocked:1,effects:[{type:'concedeArmor',amount:10,duration:1,areaSize:2}]},cooldown:6,description:'Fortaleza: Estabilizado 4 turnos, 25-35 escudo, +45% escudo recebido. Ao bloquear, concede 10 escudo para aliados próximos.'}
    ],

    // === CLÉRIGO (21) ===
    clerigo: [
        // Água (5)
        {id:'clerigo_cura_divina',catalogId:'0705000001',name:'Cura Divina',icon:'✨',class:'clerigo',element:'water',spellType:'active',castType:'targeted',targetType:'ally',paCost:3,minRange:1,maxRange:6,rangeShape:'cross',aoeType:'single',heal:{min:10,max:16,stat:'wisdom'},healScaling:{type:'socorro',threshold:30,bonus:30},description:'Cura aliado 10-16 HP. +30% cura se o alvo tiver 30% de vida ou menos (Socorro).'},
        {id:'clerigo_onda_curativa',catalogId:'0705000002',name:'Onda Curativa',icon:'🌊',class:'clerigo',element:'water',spellType:'active',castType:'targeted',targetType:'ally',paCost:4,minRange:2,maxRange:6,rangeShape:'circle',aoeType:'zone',zoneCells:[{dx:0,dy:0},{dx:-1,dy:0},{dx:1,dy:0},{dx:0,dy:-1},{dx:0,dy:1}],zoneEffects:{healCaster:false,healAlly:true},heal:{min:7,max:12,stat:'wisdom'},cooldown:2,description:'Cura em cruz (aliados).'},
        {id:'clerigo_bencao_aquas',catalogId:'0705000003',name:'Benção das Águas',icon:'💧',class:'clerigo',element:'water',spellType:'active',castType:'targeted',targetType:'ally',paCost:3,minRange:1,maxRange:5,rangeShape:'cross',aoeType:'single',heal:{min:8,max:14,stat:'wisdom'},effects:[{effectId:'cura_amplificada',level:2,target:'ally'}],cooldown:3,description:'Cura + 20% cura recebida.'},
        {id:'clerigo_purificacao',catalogId:'0705000004',name:'Purificação',icon:'✨',class:'clerigo',element:'water',spellType:'active',castType:'targeted',targetType:'ally',paCost:4,minRange:1,maxRange:5,rangeShape:'cross',aoeType:'single',effect:'removeDebuffs',heal:{min:7,max:12,stat:'wisdom'},cooldown:4,description:'Remove debuffs + cura.'},
        {id:'clerigo_diluvio_sagrado',catalogId:'0705000005',name:'Dilúvio Sagrado',icon:'💧',class:'clerigo',element:'water',spellType:'active',castType:'self',targetType:'ally',paCost:6,peCost:2,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'zone',zoneCells:[{dx:-2,dy:-2},{dx:-1,dy:-2},{dx:0,dy:-2},{dx:1,dy:-2},{dx:2,dy:-2},{dx:-2,dy:-1},{dx:-1,dy:-1},{dx:0,dy:-1},{dx:1,dy:-1},{dx:2,dy:-1},{dx:-2,dy:0},{dx:-1,dy:0},{dx:0,dy:0},{dx:1,dy:0},{dx:2,dy:0},{dx:-2,dy:1},{dx:-1,dy:1},{dx:0,dy:1},{dx:1,dy:1},{dx:2,dy:1},{dx:-2,dy:2},{dx:-1,dy:2},{dx:0,dy:2},{dx:1,dy:2},{dx:2,dy:2}],zoneEffects:{healCaster:true,healAlly:true},heal:{min:10,max:18,stat:'wisdom'},healScaling:{type:'socorro',threshold:30,bonus:30},cooldown:5,description:'Cura massiva em área 5x5. +30% cura se o alvo tiver 30% de vida ou menos (Socorro).'},
        // Fogo (5)
        {id:'clerigo_chama_purificadora',catalogId:'0705000006',name:'Chama Purificadora',icon:'🔥',class:'clerigo',element:'fire',spellType:'active',castType:'targeted',targetType:'enemy',paCost:3,minRange:2,maxRange:6,rangeShape:'cross',aoeType:'single',damage:{min:7,max:11,stat:'intelligence'},description:'Ataque sagrado.'},
        {id:'clerigo_ira_divina',catalogId:'0705000007',name:'Ira Divina',icon:'⚡',class:'clerigo',element:'fire',spellType:'active',castType:'targeted',targetType:'enemy',paCost:4,minRange:2,maxRange:6,rangeShape:'cross',aoeType:'zone',zoneCells:[{dx:0,dy:0},{dx:-1,dy:0},{dx:1,dy:0},{dx:0,dy:-1},{dx:0,dy:1}],zoneEffects:{dmgEnemy:true},damage:{min:8,max:14,stat:'intelligence'},cooldown:2,description:'Ira em cruz.'},
        {id:'clerigo_pilar_luz',catalogId:'0705000008',name:'Pilar de Luz',icon:'🔱',class:'clerigo',element:'fire',spellType:'active',castType:'targeted',targetType:'enemy',paCost:5,peCost:1,minRange:3,maxRange:8,rangeShape:'cross',aoeType:'zone',zoneCells:[{dx:0,dy:-1},{dx:0,dy:0},{dx:0,dy:1},{dx:0,dy:2}],zoneEffects:{dmgEnemy:true},damage:{min:10,max:16,stat:'intelligence'},cooldown:3,description:'Pilar vertical de luz.'},
        {id:'clerigo_julgamento_final',catalogId:'0705000009',name:'Julgamento Final',icon:'⚖️',class:'clerigo',element:'fire',spellType:'active',castType:'targeted',targetType:'enemy',paCost:5,minRange:2,maxRange:6,rangeShape:'cross',aoeType:'single',damage:{min:14,max:22,stat:'intelligence'},damageScaling:{type:'execute',threshold:30,bonus:30},cooldown:4,description:'+30% dano se o alvo tiver 30% de vida ou menos (Execute).'},
        {id:'clerigo_fogo_purificador',catalogId:'0705000010',name:'Fogo Purificador',icon:'🔥',class:'clerigo',element:'fire',spellType:'active',castType:'targeted',targetType:'enemy',paCost:6,peCost:2,minRange:3,maxRange:8,rangeShape:'circle',aoeType:'zone',zoneCells:[{dx:-1,dy:-1},{dx:0,dy:-1},{dx:1,dy:-1},{dx:-1,dy:0},{dx:0,dy:0},{dx:1,dy:0},{dx:-1,dy:1},{dx:0,dy:1},{dx:1,dy:1}],zoneEffects:{dmgEnemy:true},damage:{min:12,max:20,stat:'intelligence'},cooldown:5,description:'Fogo sagrado em área 3x3.'},
        // Ar (5)
        {id:'clerigo_brisa_curativa',catalogId:'0705000011',name:'Brisa Curativa',icon:'💨',class:'clerigo',element:'air',spellType:'active',castType:'targeted',targetType:'ally',paCost:2,minRange:1,maxRange:6,rangeShape:'cross',aoeType:'single',heal:{min:6,max:10,stat:'wisdom'},description:'Cura leve rápida.'},
        {id:'clerigo_vento_protetor',catalogId:'0705000012',name:'Vento Protetor',icon:'💨',class:'clerigo',element:'air',spellType:'active',castType:'targeted',targetType:'ally',paCost:3,minRange:1,maxRange:5,rangeShape:'cross',aoeType:'single',armorGrant:{min:8,max:14},heal:{min:5,max:8,stat:'wisdom'},cooldown:3,description:'Escudo + cura.'},
        {id:'clerigo_asas_anjo',catalogId:'0705000013',name:'Asas de Anjo',icon:'🕊️',class:'clerigo',element:'air',spellType:'active',castType:'targeted',targetType:'ally',paCost:4,minRange:1,maxRange:6,rangeShape:'cross',aoeType:'single',effect:'teleport',heal:{min:8,max:14,stat:'wisdom'},cooldown:4,description:'Teleporta aliado + cura.'},
        {id:'clerigo_tornado_sagrado',catalogId:'0705000014',name:'Tornado Sagrado',icon:'🌪️',class:'clerigo',element:'air',spellType:'active',castType:'self',targetType:'enemy',paCost:5,peCost:1,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'zone',zoneCells:[{dx:-1,dy:-1},{dx:0,dy:-1},{dx:1,dy:-1},{dx:-1,dy:0},{dx:0,dy:0},{dx:1,dy:0},{dx:-1,dy:1},{dx:0,dy:1},{dx:1,dy:1}],zoneEffects:{dmgEnemy:true},damage:{min:10,max:16,stat:'agility'},pushPull:{type:'push',distance:2,origin:'caster'},cooldown:4,description:'Tornado + empurrão.'},
        {id:'clerigo_tempestade_divina',catalogId:'0705000015',name:'Tempestade Divina',icon:'⚡',class:'clerigo',element:'air',spellType:'active',castType:'targeted',targetType:'enemy',paCost:6,peCost:2,minRange:3,maxRange:8,rangeShape:'circle',aoeType:'zone',zoneCells:[{dx:-2,dy:0},{dx:-1,dy:-1},{dx:-1,dy:0},{dx:-1,dy:1},{dx:0,dy:-2},{dx:0,dy:-1},{dx:0,dy:0},{dx:0,dy:1},{dx:0,dy:2},{dx:1,dy:-1},{dx:1,dy:0},{dx:1,dy:1},{dx:2,dy:0}],zoneEffects:{dmgEnemy:true},damage:{min:12,max:20,stat:'agility'},cooldown:5,description:'Tempestade divina em área grande.'},
        // Ativos (3)
        {id:'clerigo_aura_sagrada',catalogId:'0705000016',name:'Aura Sagrada (Toggle)',icon:'✨',class:'clerigo',element:'none',spellType:'active',castType:'self',targetType:'none',paCost:0,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'single',effect:'toggle',toggleEffect:{type:'aura_sagrada',healBonus:25,dmgPenalty:15},description:'Toggle: +25% cura, -15% dano.'},
        {id:'clerigo_escudo_fe',catalogId:'0705000017',name:'Escudo de Fé',icon:'🛡️',class:'clerigo',element:'none',spellType:'active',castType:'targeted',targetType:'ally',paCost:3,minRange:1,maxRange:6,rangeShape:'cross',aoeType:'single',armorGrant:{min:12,max:18},effects:[{effectId:'escudo_recebido',level:1,target:'ally'}],cooldown:3,description:'Escudo + 15% escudo recebido.'},
        {id:'clerigo_ressurreicao',catalogId:'0705000018',name:'Ressurreição',icon:'✝️',class:'clerigo',element:'none',spellType:'active',castType:'targeted',targetType:'ally',paCost:6,peCost:3,minRange:1,maxRange:4,rangeShape:'cross',aoeType:'single',effect:'revive',healPercent:0.5,cooldown:8,description:'Revive aliado zumbi com 50% HP.'},
        // Ativos extras (2)
        {id:'clerigo_bencao',catalogId:'0705000022',name:'Benção',icon:'🙏',class:'clerigo',element:'none',spellType:'active',castType:'targeted',targetType:'ally',paCost:2,minRange:1,maxRange:6,rangeShape:'cross',aoeType:'single',effects:[{effectId:'cura_amplificada',level:2,target:'ally'}],cooldown:4,description:'Aliado ganha +20% cura recebida por 3 turnos.'},
        {id:'clerigo_condenacao',catalogId:'0705000023',name:'Condenação',icon:'⛓️',class:'clerigo',element:'none',spellType:'active',castType:'targeted',targetType:'enemy',paCost:3,minRange:2,maxRange:6,rangeShape:'cross',aoeType:'single',effects:[{effectId:'enfraquecido',level:2,target:'enemy'}],cooldown:4,description:'Inimigo sofre -15% dano causado por 2 turnos.'},
        // Passivos (5)
        {id:'clerigo_passivo_vinculo_sagrado',catalogId:'0705000019',name:'Vínculo Sagrado',icon:'🔗',class:'clerigo',element:'none',spellType:'passive',castType:'self',targetType:'none',passiveEffect:{onHitTaken:{enabled:true,minDamage:8,effects:[{type:'healAllies',percent:15}]}},description:'Ao sofrer 8+ dmg, cura aliados em 15% do dano.'},
        {id:'clerigo_passivo_martir',catalogId:'0705000020',name:'Mártir',icon:'✝️',class:'clerigo',element:'none',spellType:'passive',castType:'self',targetType:'none',passiveEffect:{support:15,heal_received:15},description:'+15% cura realizada e recebida.'},
        // Passivos extras (3)
        {id:'clerigo_passivo_conexao_divina',catalogId:'0705000024',name:'Conexão Divina',icon:'🔮',class:'clerigo',element:'none',spellType:'passive',castType:'self',targetType:'none',passiveEffect:{healingDone:10},description:'+10% cura realizada.'},
        {id:'clerigo_passivo_protecao_sagrada',catalogId:'0705000025',name:'Proteção Sagrada',icon:'🛡️',class:'clerigo',element:'none',spellType:'passive',castType:'self',targetType:'none',passiveEffect:{combatStartArmor:8},description:'Começa combate com 8 de escudo.'},
        {id:'clerigo_passivo_serenidade',catalogId:'0705000026',name:'Serenidade',icon:'☮️',class:'clerigo',element:'none',spellType:'passive',castType:'self',targetType:'none',passiveEffect:{noDamageTakenBonus:{gainPA:1}},description:'+1 PA se não sofreu dano no turno anterior.'},
        // Suporte extra (1)
        {id:'clerigo_inspiracao_divina',catalogId:'0705000027',name:'Inspiração Divina',icon:'🌟',class:'clerigo',element:'none',spellType:'active',castType:'targeted',targetType:'ally',paCost:3,minRange:1,maxRange:6,rangeShape:'cross',aoeType:'single',peGrant:1,effects:[{effectId:'poderoso',level:1}],cooldown:3,description:'Concede 1 PE e +10% de dano causado ao aliado por 2 turnos.'},
        // DOM (1)
        {id:'clerigo_dom_avatar_luz',catalogId:'0705000021',name:'DOM: Avatar da Luz',icon:'✨',class:'clerigo',element:'none',spellType:'active',castType:'self',targetType:'ally',paCost:0,peCost:3,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'zone',zoneCells:[{dx:-2,dy:-2},{dx:-1,dy:-2},{dx:0,dy:-2},{dx:1,dy:-2},{dx:2,dy:-2},{dx:-2,dy:-1},{dx:-1,dy:-1},{dx:0,dy:-1},{dx:1,dy:-1},{dx:2,dy:-1},{dx:-2,dy:0},{dx:-1,dy:0},{dx:0,dy:0},{dx:1,dy:0},{dx:2,dy:0},{dx:-2,dy:1},{dx:-1,dy:1},{dx:0,dy:1},{dx:1,dy:1},{dx:2,dy:1},{dx:-2,dy:2},{dx:-1,dy:2},{dx:0,dy:2},{dx:1,dy:2},{dx:2,dy:2}],zoneEffects:{healCaster:true,healAlly:true},heal:{min:20,max:30,stat:'wisdom'},armorGrant:{min:16,max:25},effects:[{effectId:'cura_amplificada',level:5,target:'self'}],cooldown:6,description:'Avatar: Cura massiva 5x5 (20-30 HP), 16-25 escudo, +50% cura recebida 3 turnos.'}
    ],

    // === BERSERKER (21) ===
    berserker: [
        // Fogo (5)
        {id:'berserker_furia_sangrenta',catalogId:'0706000001',name:'Fúria Sangrenta',icon:'💢',class:'berserker',element:'fire',spellType:'active',castType:'targeted',targetType:'enemy',paCost:5,minRange:1,maxRange:1,rangeShape:'cross',aoeType:'single',damage:{min:14,max:22,stat:'strength'},berserk:100,selfDamage:{type:'percent',amount:8},onKill:{enabled:true,effects:[{type:'stealPA',amount:2},{type:'stealHP',percent:20}]},description:'Berserk +100%. Auto-dano 8%. Rouba PA e HP ao matar.'},
        {id:'berserker_chama_desesperada',catalogId:'0706000002',name:'Chama Desesperada',icon:'🔥',class:'berserker',element:'fire',spellType:'active',castType:'targeted',targetType:'enemy',paCost:4,minRange:1,maxRange:2,rangeShape:'circle',aoeType:'single',damage:{min:10,max:16,stat:'intelligence'},damageScaling:{type:'berserk',threshold:50,bonus:50},description:'+50% dano se você tiver 50% de vida ou menos (Berserk).'},
        {id:'berserker_aniquilacao',catalogId:'0706000003',name:'Aniquilação',icon:'💀',class:'berserker',element:'fire',spellType:'active',castType:'targeted',targetType:'enemy',paCost:6,minRange:1,maxRange:1,rangeShape:'cross',aoeType:'single',damage:{min:22,max:32,stat:'strength'},damageScaling:{type:'berserk',threshold:50,bonus:50},selfDamage:{type:'percent',amount:20},cooldown:4,description:'+50% dano se HP ≤50% (Berserk). Auto-dano 20%.'},
        {id:'berserker_imolacao',catalogId:'0706000004',name:'Imolação',icon:'☠️',class:'berserker',element:'fire',spellType:'active',castType:'self',targetType:'enemy',paCost:5,peCost:1,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'zone',zoneCells:[{dx:-1,dy:-1},{dx:0,dy:-1},{dx:1,dy:-1},{dx:-1,dy:0},{dx:0,dy:0},{dx:1,dy:0},{dx:-1,dy:1},{dx:0,dy:1},{dx:1,dy:1}],zoneEffects:{dmgEnemy:true},damage:{min:10,max:16,stat:'intelligence'},selfDamage:{type:'percent',amount:15},berserk:100,cooldown:3,description:'Explosão 3x3. Berserk +100%. Auto-dano 15%.'},
        {id:'berserker_inferno_raiva',catalogId:'0706000005',name:'Inferno de Raiva',icon:'👹',class:'berserker',element:'fire',spellType:'active',castType:'targeted',targetType:'enemy',paCost:6,peCost:2,minRange:1,maxRange:3,rangeShape:'circle',aoeType:'zone',zoneCells:[{dx:-1,dy:-1},{dx:0,dy:-1},{dx:1,dy:-1},{dx:-1,dy:0},{dx:0,dy:0},{dx:1,dy:0},{dx:-1,dy:1},{dx:0,dy:1},{dx:1,dy:1}],zoneEffects:{dmgEnemy:true},damage:{min:14,max:22,stat:'intelligence'},damageScaling:{type:'berserk',threshold:50,bonus:40},selfDamage:{type:'percent',amount:12},onKill:{enabled:true,effects:[{type:'stealPA',amount:2},{type:'stealHP',percent:30}]},cooldown:5,description:'+40% dano se HP ≤50% (Berserk). Auto-dano 12%. Rouba PA e HP ao matar.'},
        // Terra (5)
        {id:'berserker_golpe_brutal',catalogId:'0706000006',name:'Golpe Brutal',icon:'👊',class:'berserker',element:'earth',spellType:'active',castType:'targeted',targetType:'enemy',paCost:3,minRange:1,maxRange:1,rangeShape:'cross',aoeType:'single',damage:{min:7,max:11,stat:'strength'},berserk:100,onKill:{enabled:true,effects:[{type:'stealPA',amount:1}]},description:'Berserk +100%. Rouba 1 PA ao matar.'},
        {id:'berserker_terremoto_raiva',catalogId:'0706000007',name:'Terremoto de Raiva',icon:'🌍',class:'berserker',element:'earth',spellType:'active',castType:'self',targetType:'enemy',paCost:5,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'zone',zoneCells:[{dx:-2,dy:0},{dx:-1,dy:-1},{dx:-1,dy:0},{dx:-1,dy:1},{dx:0,dy:-2},{dx:0,dy:-1},{dx:0,dy:0},{dx:0,dy:1},{dx:0,dy:2},{dx:1,dy:-1},{dx:1,dy:0},{dx:1,dy:1},{dx:2,dy:0}],zoneEffects:{dmgEnemy:true},damage:{min:10,max:16,stat:'strength'},berserk:100,cooldown:3,description:'Terremoto. Berserk +100%.'},
        {id:'berserker_esmagamento',catalogId:'0706000008',name:'Esmagamento',icon:'💥',class:'berserker',element:'earth',spellType:'active',castType:'targeted',targetType:'enemy',paCost:4,minRange:1,maxRange:1,rangeShape:'cross',aoeType:'single',damage:{min:10,max:16,stat:'strength'},bonusVsArmored:60,selfDamage:{type:'flat',amount:5},description:'+60% vs escudo. Auto-dano 5.'},
        {id:'berserker_pele_ferro',catalogId:'0706000009',name:'Pele de Ferro',icon:'🛡️',class:'berserker',element:'earth',spellType:'active',castType:'self',targetType:'none',paCost:3,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'single',armorGrant:{min:10,max:16},onHitTaken:{enabled:true,minDamage:8,effects:[{type:'damageBonus',percent:20,duration:2}]},cooldown:4,description:'Escudo. Ao sofrer 8+, ganha +20% dmg 2 turnos.'},
        {id:'berserker_abalo_sismico',catalogId:'0706000010',name:'Abalo Sísmico',icon:'🌍',class:'berserker',element:'earth',spellType:'active',castType:'targeted',targetType:'enemy',paCost:6,peCost:2,minRange:1,maxRange:2,rangeShape:'circle',aoeType:'zone',zoneCells:[{dx:-1,dy:-1},{dx:0,dy:-1},{dx:1,dy:-1},{dx:-1,dy:0},{dx:0,dy:0},{dx:1,dy:0},{dx:-1,dy:1},{dx:0,dy:1},{dx:1,dy:1}],zoneEffects:{dmgEnemy:true},damage:{min:14,max:22,stat:'strength'},damageScaling:{type:'berserk',threshold:50,bonus:40},selfDamage:{type:'percent',amount:10},onKill:{enabled:true,effects:[{type:'stealArmor',amount:12}]},cooldown:5,description:'Abalo 3x3. +40% dano se HP ≤50% (Berserk). Auto-dano 10%. Rouba escudo ao matar.'},
        // Ar (5)
        {id:'berserker_tornado_furia',catalogId:'0706000011',name:'Tornado de Fúria',icon:'🌪️',class:'berserker',element:'air',spellType:'active',castType:'self',targetType:'enemy',paCost:4,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'zone',zoneCells:[{dx:-1,dy:-1},{dx:0,dy:-1},{dx:1,dy:-1},{dx:-1,dy:0},{dx:0,dy:0},{dx:1,dy:0},{dx:-1,dy:1},{dx:0,dy:1},{dx:1,dy:1}],zoneEffects:{dmgEnemy:true},damage:{min:8,max:14,stat:'agility'},berserk:100,cooldown:2,description:'Tornado 3x3. Berserk +100%.'},
        {id:'berserker_velocidade_mortal',catalogId:'0706000012',name:'Velocidade Mortal',icon:'⚔️',class:'berserker',element:'air',spellType:'active',castType:'targeted',targetType:'enemy',paCost:3,minRange:1,maxRange:3,rangeShape:'line',aoeType:'single',damage:{min:7,max:11,stat:'agility'},advancedStatus:[{type:'ensaboado',duration:1}],onKill:{enabled:true,effects:[{type:'stealPM',amount:1}]},description:'Ataque rápido. Ensaboado. Rouba PM ao matar.'},
        {id:'berserker_ciclone_dor',catalogId:'0706000013',name:'Ciclone de Dor',icon:'🌀',class:'berserker',element:'air',spellType:'active',castType:'self',targetType:'enemy',paCost:5,peCost:1,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'zone',zoneCells:[{dx:-2,dy:0},{dx:-1,dy:-1},{dx:-1,dy:0},{dx:-1,dy:1},{dx:0,dy:-2},{dx:0,dy:-1},{dx:0,dy:0},{dx:0,dy:1},{dx:0,dy:2},{dx:1,dy:-1},{dx:1,dy:0},{dx:1,dy:1},{dx:2,dy:0}],zoneEffects:{dmgEnemy:true},damage:{min:10,max:16,stat:'agility'},damageScaling:{type:'berserk',threshold:50,bonus:30},selfDamage:{type:'percent',amount:8},cooldown:4,description:'Ciclone. +30% dano se HP ≤50% (Berserk). Auto-dano 8%.'},
        {id:'berserker_tempestade_sangue',catalogId:'0706000014',name:'Tempestade de Sangue',icon:'🩸',class:'berserker',element:'air',spellType:'active',castType:'targeted',targetType:'enemy',paCost:5,minRange:2,maxRange:4,rangeShape:'circle',aoeType:'zone',zoneCells:[{dx:-1,dy:-1},{dx:0,dy:-1},{dx:1,dy:-1},{dx:-1,dy:0},{dx:0,dy:0},{dx:1,dy:0},{dx:-1,dy:1},{dx:0,dy:1},{dx:1,dy:1}],zoneEffects:{dmgEnemy:true,lifeSteal:true},damage:{min:10,max:16,stat:'agility'},berserk:100,selfDamage:{type:'percent',amount:10},cooldown:4,description:'Tempestade 3x3. Life steal. Berserk. Auto-dano 10%.'},
        {id:'berserker_vendaval_caos',catalogId:'0706000015',name:'Vendaval do Caos',icon:'💨',class:'berserker',element:'air',spellType:'active',castType:'self',targetType:'enemy',paCost:6,peCost:2,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'zone',zoneCells:[{dx:-2,dy:-2},{dx:-1,dy:-2},{dx:0,dy:-2},{dx:1,dy:-2},{dx:2,dy:-2},{dx:-2,dy:-1},{dx:-1,dy:-1},{dx:0,dy:-1},{dx:1,dy:-1},{dx:2,dy:-1},{dx:-2,dy:0},{dx:-1,dy:0},{dx:0,dy:0},{dx:1,dy:0},{dx:2,dy:0},{dx:-2,dy:1},{dx:-1,dy:1},{dx:0,dy:1},{dx:1,dy:1},{dx:2,dy:1},{dx:-2,dy:2},{dx:-1,dy:2},{dx:0,dy:2},{dx:1,dy:2},{dx:2,dy:2}],zoneEffects:{dmgEnemy:true},damage:{min:12,max:20,stat:'agility'},damageScaling:{type:'berserk',threshold:50,bonus:50},selfDamage:{type:'percent',amount:15},onKill:{enabled:true,effects:[{type:'stealPA',amount:2},{type:'stealPM',amount:1},{type:'stealHP',percent:30}]},cooldown:5,description:'Vendaval 5x5. +50% dano se HP ≤50% (Berserk). Auto-dano 15%. Rouba tudo ao matar.'},
        // Ativos (3)
        {id:'berserker_frenesi',catalogId:'0706000016',name:'Frenesi (Toggle)',icon:'💢',class:'berserker',element:'none',spellType:'active',castType:'self',targetType:'none',paCost:0,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'single',effect:'toggle',toggleEffect:{type:'frenesi',damageBonus:40,advancedStatus:'ensaboado'},description:'Toggle: +40% dmg, Ensaboado permanente.'},
        {id:'berserker_salto_devastador',catalogId:'0706000017',name:'Salto Devastador',icon:'💥',class:'berserker',element:'none',spellType:'active',castType:'targeted',targetType:'none',paCost:4,minRange:2,maxRange:6,rangeShape:'circle',aoeType:'zone',zoneCells:[{dx:-1,dy:-1},{dx:0,dy:-1},{dx:1,dy:-1},{dx:-1,dy:0},{dx:0,dy:0},{dx:1,dy:0},{dx:-1,dy:1},{dx:0,dy:1},{dx:1,dy:1}],zoneEffects:{dmgEnemy:true},effect:'teleport',damage:{min:10,max:16,stat:'strength'},cooldown:3,description:'Teleporta + AoE 10-16 dmg.'},
        {id:'berserker_investida_sangrenta',catalogId:'0706000018',name:'Investida Sangrenta',icon:'🩸',class:'berserker',element:'none',spellType:'active',castType:'targeted',targetType:'enemy',paCost:5,minRange:2,maxRange:4,rangeShape:'line',aoeType:'single',effect:'swapPosition',checkEstabilizado:true,damage:{min:16,max:22,stat:'strength'},selfDamage:{type:'percent',amount:10},onKill:{enabled:true,effects:[{type:'stealHP',percent:40}]},cooldown:4,description:'Troca posição + dano. Auto-dano 10%. Rouba 40% HP ao matar.'},
        // Ativos extras (2)
        {id:'berserker_sede_destruicao',catalogId:'0706000022',name:'Sede de Destruição',icon:'💀',class:'berserker',element:'none',spellType:'active',castType:'self',targetType:'none',paCost:2,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'single',selfDamage:{type:'percent',amount:10},effect:'gainPA',gainPA:2,cooldown:4,description:'Sacrifica 10% HP, ganha +2 PA neste turno.'},
        {id:'berserker_rugido_terror',catalogId:'0706000023',name:'Rugido Aterrorizante',icon:'😱',class:'berserker',element:'none',spellType:'active',castType:'self',targetType:'enemy',paCost:3,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'zone',zoneCells:[{dx:-1,dy:-1},{dx:0,dy:-1},{dx:1,dy:-1},{dx:-1,dy:0},{dx:0,dy:0},{dx:1,dy:0},{dx:-1,dy:1},{dx:0,dy:1},{dx:1,dy:1}],zoneEffects:{dmgEnemy:false},effects:[{effectId:'enfraquecido',level:2,target:'enemy'}],cooldown:4,description:'Inimigos em 3x3: -15% dano causado por 2 turnos.'},
        // Passivos (5)
        {id:'berserker_passivo_sede_sangue',catalogId:'0706000019',name:'Sede de Sangue',icon:'🩸',class:'berserker',element:'none',spellType:'passive',castType:'self',targetType:'none',passiveEffect:{onKill:{enabled:true,effects:[{type:'stealHP',percent:25},{type:'stealPA',amount:1}]},onHitTaken:{enabled:true,minDamage:10,effects:[{type:'damageBonus',percent:15,duration:2}]}},description:'Ao matar: rouba 25% HP e 1 PA. Ao sofrer 10+: +15% dmg.'},
        {id:'berserker_passivo_ultimo_suspiro',catalogId:'0706000020',name:'Último Suspiro',icon:'💀',class:'berserker',element:'none',spellType:'passive',castType:'self',targetType:'none',passiveEffect:{onHpBelow:{threshold:20,oncePerCombat:true,effects:[{type:'damageBonus',percent:100,duration:3},{type:'heal',percent:30}]}},description:'Ao chegar em 20% HP (1x por combate): +100% dmg por 3 turnos, cura 30%.'},
        // Passivos extras (3)
        {id:'berserker_passivo_pele_grossa',catalogId:'0706000024',name:'Pele Grossa',icon:'🛡️',class:'berserker',element:'none',spellType:'passive',castType:'self',targetType:'none',passiveEffect:{damageReduction:10},description:'-10% dano recebido.'},
        {id:'berserker_passivo_adrenalina',catalogId:'0706000025',name:'Adrenalina',icon:'💉',class:'berserker',element:'none',spellType:'passive',castType:'self',targetType:'none',passiveEffect:{hpLowDamageBonus:{per10Percent:2}},description:'+2% dano para cada 10% de HP perdido.'},
        {id:'berserker_passivo_ultimo_homem',catalogId:'0706000026',name:'Último Homem',icon:'🏴',class:'berserker',element:'none',spellType:'passive',castType:'self',targetType:'none',passiveEffect:{lastManStanding:{bonusPA:3,bonusPM:2}},description:'Quando é o último aliado vivo: +3 PA e +2 PM.'},
        // DOM (1)
        {id:'berserker_dom_forma_berserk',catalogId:'0706000021',name:'DOM: Forma Berserk',icon:'👹',class:'berserker',element:'none',spellType:'active',castType:'self',targetType:'none',paCost:0,peCost:3,minRange:0,maxRange:0,rangeShape:'circle',aoeType:'single',selfDamage:{type:'percent',amount:25},effects:[{effectId:'poderoso',level:5,target:'self'}],advancedStatus:[{type:'ensaboado',duration:4}],onKill:{enabled:true,effects:[{type:'stealPA',amount:3},{type:'stealPM',amount:2},{type:'stealHP',percent:50},{type:'stealArmor',amount:15}]},onHitTaken:{enabled:true,minDamage:8,effects:[{type:'damageBonus',percent:25,duration:2}]},cooldown:6,description:'Forma Berserk: Auto-dano 25%, +50% dmg, Ensaboado 4 turnos. Ao matar: rouba TUDO. Ao sofrer dmg: +25% dmg.'}
    ]
};
