// ========== FEITIÇOS DO ATIRADOR ==========
// 26 feitiços: 15 elementais (air, fire, earth × 5) + 5 ativos + 5 passivos + 1 DOM
// RECALIBRADO para HP base 50

const DB_FEITICOS_ATIRADOR = [
    // === AR (5) ===
    { id: 'atirador_flecha_vento', catalogId: '0702000001', name: 'Flecha de Vento', icon: '🏹', class: 'atirador', element: 'air', spellType: 'active', castType: 'targeted', targetType: 'enemy', needsTarget: false, paCost: 3, minRange: 1, maxRange: 8, rangeShape: 'circle', aoeType: 'single', damage: { min: 7, max: 11, stat: 'agility' }, closeRangeEffect: { maxRange: 3, blockReduction: { flat: 5, percentOfLevel: 15, duration: 2 } }, castsPerTurn: 2, description: 'Flecha de Ar em círculo (1-8 células). Se lançada a 3 células ou menos, reduz o Bloqueio do alvo em 5 + 15% do Nível do alvo por 2 turnos (pode ficar negativo). 2 usos por turno.' },
    { id: 'atirador_rajada_ar', catalogId: '0702000002', name: 'Rajada de Ar', icon: '🌪️', class: 'atirador', element: 'air', spellType: 'active', castType: 'targeted', targetType: 'enemy', needsTarget: false, paCost: 4, minRange: 3, maxRange: 5, rangeShape: 'line', rangeModifiable: true, aoeType: 'zone', zoneCells: [{dx:0,dy:0},{dx:1,dy:0},{dx:2,dy:0}], zoneDirectional: true, zoneEffects: {dmgCaster:false,dmgAlly:false,dmgEnemy:true,healCaster:false,healAlly:false,healEnemy:false,lifeSteal:false}, damage: { min: 6, max: 10, stat: 'agility' }, pushPull: { type: 'push', distance: 3 }, cooldown: 1, description: 'Rajada de Ar em linha (3-5 células, modificável). Atinge 3 células consecutivas na direção do lançamento, causa 6-10 de dano e empurra 3 células. Recarga: 1 turno.' },
    { id: 'atirador_laminas_vento', catalogId: '0702000004', name: 'Lâminas de Vento', icon: '💨', class: 'atirador', element: 'air', spellType: 'active', castType: 'targeted', targetType: 'enemy', needsTarget: false, paCost: 3, minRange: 4, maxRange: 6, rangeShape: 'circle', rangeModifiable: true, aoeType: 'zone', zoneCells: [{dx:-1,dy:-1},{dx:-1,dy:1},{dx:1,dy:-1},{dx:1,dy:1}], zoneEffects: {dmgCaster:false,dmgAlly:false,dmgEnemy:true,healCaster:false,healAlly:false,healEnemy:false,lifeSteal:false}, damage: { min: 6, max: 10, stat: 'agility' }, castsPerTurn: 1, description: 'Lâminas de vento em círculo (4-6 células, modificável). Atinge apenas as 4 células diagonais ao ponto visado. 1 uso por turno.' },
    { id: 'atirador_tempestade_precisao', catalogId: '0702000005', name: 'Tempestade de Precisão', icon: '⚡', class: 'atirador', element: 'air', spellType: 'active', castType: 'targeted', targetType: 'enemy', paCost: 5, pmCost: 2, minRange: 5, maxRange: 12, rangeShape: 'line', aoeType: 'single', damage: { min: 18, max: 28, stat: 'agility' }, damageScaling: { type: 'intacto', bonus: 20 }, initialCooldown: 1, cooldown: 1, castsPerTurn: 1, description: 'Tiro devastador de Ar em linha reta (5-12 células). Causa 18-28 de dano. +20% de dano se o alvo estiver com vida cheia (Intacto). Recarga: 1 turno. Disponível a partir do turno 2.' },
    { id: 'atirador_rajada_continua', catalogId: '0702000003', name: 'Rajada Contínua', icon: '🌀', class: 'atirador', element: 'air', spellType: 'active', castType: 'targeted', targetType: 'enemy', paCost: 5, peCost: 1, minRange: 5, maxRange: 7, rangeShape: 'line', rangeModifiable: true, aoeType: 'single', damage: { min: 9, max: 13, stat: 'agility' }, stackMechanic: { type: 'caster', maxStacks: 2, damageBonus: [0, 15, 30], stackDuration: 3 }, cooldown: 2, description: 'Rajada de Ar contínua em linha reta (5-7 células, modificável). Causa 9-13 de dano. Stack no lançador: cada uso consecutivo aumenta o dano (+15%, +30%). Stack dura 3 turnos — expira se não for usada novamente. Recarga: 2 turnos.' },

    // === FOGO (5) ===
    { id: 'atirador_tiro_incendiario', catalogId: '0702000008', name: 'Tiro Incendiário', icon: '🔥', class: 'atirador', element: 'fire', spellType: 'active', castType: 'targeted', targetType: 'both', targetAlly: true, paCost: 2, minRange: 1, maxRange: 5, rangeShape: 'circle', rangeModifiable: true, aoeType: 'single', damage: { min: 7, max: 11, stat: 'intelligence' }, pmSteal: 1, castsPerTarget: 2, castsPerTurn: 4, description: 'Tiro de Fogo em círculo (1-5 células, modificável). Pode atingir aliados e inimigos. Rouba 1 PM do alvo se sobreviver ao golpe (contestado por Vontade). 2 usos por alvo, 4 por turno.' },
    { id: 'atirador_marca_chamas', catalogId: '0702000009', name: 'Marca de Chamas', icon: '🎯', class: 'atirador', element: 'fire', spellType: 'active', castType: 'targeted', targetType: 'enemy', paCost: 4, minRange: 3, maxRange: 5, rangeShape: 'circle', rangeModifiable: true, aoeType: 'single', damage: { min: 8, max: 14, stat: 'intelligence' }, effects: [{ effectId: 'cura_reduzida', level: 1, target: 'enemy' }], castsPerTurn: 2, description: 'Marca de Fogo em círculo (3-5 células, modificável). Aplica Cura Reduzida: -8% de cura recebida por 1 turno (acumula). 2 usos por turno.' },
    { id: 'atirador_disparo_flamejante', catalogId: '0702000010', name: 'Disparo Flamejante', icon: '☄️', class: 'atirador', element: 'fire', spellType: 'active', castType: 'targeted', targetType: 'enemy', paCost: 3, minRange: 2, maxRange: 6, rangeShape: 'circle', aoeType: 'single', damage: { min: 8, max: 14, stat: 'intelligence' }, castsPerTurn: 3, castsPerTarget: 2, description: 'Disparo concentrado de Fogo de alvo único em círculo (2-6 células). 3 usos por turno, 2 por alvo.' },
    { id: 'atirador_flecha_explosiva', catalogId: '0702000006', name: 'Flecha Explosiva', icon: '💥', class: 'atirador', element: 'fire', spellType: 'active', castType: 'targeted', targetType: 'enemy', needsTarget: false, paCost: 5, minRange: 4, maxRange: 6, rangeShape: 'circle', aoeType: 'zone', zoneCells: [{dx:-2,dy:0},{dx:-1,dy:-1},{dx:-1,dy:0},{dx:-1,dy:1},{dx:0,dy:-2},{dx:0,dy:-1},{dx:0,dy:0},{dx:0,dy:1},{dx:0,dy:2},{dx:1,dy:-1},{dx:1,dy:0},{dx:1,dy:1},{dx:2,dy:0}], zoneEffects: {dmgCaster:false,dmgAlly:true,dmgEnemy:true,healCaster:false,healAlly:false,healEnemy:false,lifeSteal:false}, damage: { min: 10, max: 16, stat: 'intelligence' }, description: 'Flecha de Fogo que explode numa área diamante de raio 2 (13 células). Não precisa de alvo — pode ser lançada no chão. A explosão atinge tanto aliados quanto inimigos na zona.' },
    { id: 'atirador_flecha_venenosa', catalogId: '0702000007', name: 'Flecha Venenosa', icon: '☠️', class: 'atirador', element: 'fire', spellType: 'active', castType: 'targeted', targetType: 'enemy', paCost: 5, peCost: 1, minRange: 5, maxRange: 7, rangeShape: 'line', rangeModifiable: true, aoeType: 'single', damage: { min: 8, max: 12, stat: 'intelligence' }, effects: [{ effectId: 'veneno_zefir', level: 1, target: 'enemy' }], cooldown: 2, description: 'Flecha envenenada de Fogo em linha reta (5-7 células, modificável). Aplica Veneno: 3 de dano por turno durante 3 turnos. Repetir no mesmo alvo escala o veneno: Nv2 (5/turno), Nv3 (8/turno).' },

    // === TERRA (5) ===
    { id: 'atirador_flecha_perfurante', catalogId: '0702000011', name: 'Flecha Perfurante', icon: '🏹', class: 'atirador', element: 'earth', spellType: 'active', castType: 'targeted', targetType: 'enemy', paCost: 2, pmCost: 1, minRange: 2, maxRange: 5, rangeShape: 'diagonal', rangeModifiable: true, aoeType: 'single', damage: { min: 5, max: 9, stat: 'strength' }, doubleHitIfArmored: true, castsPerTurn: 1, description: 'Flecha de Terra em diagonal (2-5 células, modificável). Causa 5-9 de dano. Se o alvo tiver escudo, recebe o hit duas vezes. 1 uso por turno.' },
    { id: 'atirador_marca_eterea', catalogId: '0702000012', name: 'Marca Etérea', icon: '👻', class: 'atirador', element: 'earth', spellType: 'active', castType: 'targeted', targetType: 'both', targetAlly: true, paCost: 2, minRange: 3, maxRange: 6, rangeShape: 'circle', rangeModifiable: true, aoeType: 'single', damage: { min: 4, max: 7, stat: 'strength' }, damageEnemyOnly: true, advancedStatus: [{ type: 'transparente', duration: 1, tickOnCasterTurn: true }], castsPerTurn: 2, description: 'Marca etérea em círculo (3-6 células, modificável). Em inimigos: causa 4-7 de dano e torna Transparente por 1 turno. Em aliados: apenas torna Transparente (sem dano). Transparente = não bloqueia Linha de Visão. 2 usos por turno.' },
    { id: 'atirador_tiro_estilhaçante', catalogId: '0702000013', name: 'Tiro Estilhaçante', icon: '💥', class: 'atirador', element: 'earth', spellType: 'active', castType: 'targeted', targetType: 'enemy', paCost: 5, minRange: 3, maxRange: 6, rangeShape: 'star', rangeModifiable: true, aoeType: 'single', damage: { min: 6, max: 10, stat: 'strength' }, ricochete: { bounces: 2, decayPercent: -25, maxRange: 2, sameTargetOnce: true, requiresLoS: true }, castsPerTurn: 2, description: 'Tiro de Terra em linha e diagonal (3-6 células, modificável). Causa 6-10 de dano. Ricochete: salta para até 2 alvos em 2 células, +25% de dano por salto. Necessita LoS. Não repete alvo. 2 usos por turno.' },
    { id: 'atirador_tiro_erosivo', catalogId: '0702000015', name: 'Tiro Erosivo', icon: '🪨', class: 'atirador', element: 'earth', spellType: 'active', castType: 'targeted', targetType: 'enemy', paCost: 4, minRange: 2, maxRange: 5, rangeShape: 'circle', rangeModifiable: true, aoeType: 'single', damage: { min: 7, max: 11, stat: 'strength' }, effects: [{ effectId: 'erosao_dano', level: 1, target: 'enemy' }], castsPerTurn: 2, description: 'Tiro de Terra erosivo em círculo (2-5 células, modificável). Causa 7-11 de dano e aplica Erosão: -3% de dano final causado pelo alvo (acumula). 2 usos por turno.' },
    { id: 'atirador_tiro_crescente', catalogId: '0702000014', name: 'Tiro Crescente', icon: '📈', class: 'atirador', element: 'earth', spellType: 'active', castType: 'targeted', targetType: 'enemy', paCost: 5, peCost: 1, minRange: 5, maxRange: 7, rangeShape: 'line', rangeModifiable: true, aoeType: 'single', damage: { min: 10, max: 14, stat: 'strength' }, stackMechanic: { type: 'target', maxStacks: 2, damageBonus: [0, 30, 60], stackDuration: 3 }, cooldown: 2, description: 'Tiro de Terra crescente em linha reta (5-7 células, modificável). Causa 10-14 de dano. Repetir no mesmo alvo escala o dano: +30% (2o uso), +60% (3o uso). Stack dura 3 turnos — expira se não for reaplicada. Trocar de alvo reseta. Recarga: 2 turnos.' },

    // === ATIVOS (3) ===
    { id: 'atirador_rolamento_tatico', catalogId: '0702000016', name: 'Rolamento Tático', icon: '🤸', class: 'atirador', element: 'none', spellType: 'active', castType: 'targeted', targetType: 'none', needsTarget: false, paCost: 2, peCost: 2, minRange: 1, maxRange: 3, rangeShape: 'line', aoeType: 'single', effect: 'dashThroughCells', requiresEmptyCell: true, cooldown: 2, description: 'Rola em linha reta até a célula selecionada (1-3 células). Passa por cada célula no caminho ignorando tackle. Se houver armadilha no caminho, o movimento para e a armadilha é ativada. Custa 2 PA e 2 PE.' },
    { id: 'atirador_sombra_fugaz', catalogId: '0702000017', name: 'Sombra Fugaz', icon: '👤', class: 'atirador', element: 'none', spellType: 'active', castType: 'self', targetType: 'none', paCost: 3, minRange: 0, maxRange: 0, rangeShape: 'circle', aoeType: 'single', advancedStatus: [{ type: 'ensaboado', duration: 2 }], cooldown: 3, description: 'Desaparece nas sombras. Concede Ensaboado por 2 turnos (imune a tackle ao se mover adjacente a inimigos).' },
    { id: 'atirador_empurrao', catalogId: '0702000018', name: 'Empurrão', icon: '👋', class: 'atirador', element: 'none', spellType: 'active', castType: 'targeted', targetType: 'enemy', paCost: 2, minRange: 1, maxRange: 1, rangeShape: 'cross', aoeType: 'single', pushPull: { type: 'push', distance: 3 }, cooldown: 2, description: 'Empurra um inimigo adjacente (1 célula) 3 células para longe em linha reta.' },

    // === ATIVOS EXTRAS (2) ===
    { id: 'atirador_mira_certeira', catalogId: '0702000022', name: 'Mira Certeira', icon: '🎯', class: 'atirador', element: 'none', spellType: 'active', castType: 'self', targetType: 'none', paCost: 2, minRange: 0, maxRange: 0, rangeShape: 'circle', aoeType: 'single', effects: [{ effectId: 'critico_boost', level: 2, target: 'self' }], cooldown: 3, description: 'Concentra a mira. Concede +30% de chance de acerto crítico por 2 turnos.' },
    { id: 'atirador_recuar', catalogId: '0702000023', name: 'Recuar', icon: '🏃', class: 'atirador', element: 'none', spellType: 'active', castType: 'self', targetType: 'none', paCost: 2, minRange: 0, maxRange: 0, rangeShape: 'circle', aoeType: 'single', effect: 'moveAway', moveDistance: 3, cooldown: 3, description: 'Recua rapidamente 3 células na direção oposta ao inimigo mais próximo.' },

    // === PASSIVOS (5) ===
    { id: 'atirador_passivo_olho_aguia', catalogId: '0702000019', name: 'Olho de Águia', icon: '👁️', class: 'atirador', element: 'none', spellType: 'passive', castType: 'self', targetType: 'none', passiveEffect: { rangeBonus: 2 }, description: 'Visão aguçada. Aumenta o alcance de todos os feitiços em +2 células permanentemente.' },
    { id: 'atirador_passivo_mobilidade', catalogId: '0702000020', name: 'Mobilidade Superior', icon: '🏃', class: 'atirador', element: 'none', spellType: 'passive', castType: 'self', targetType: 'none', passiveEffect: { maxPm: 1 }, description: 'Pernas ágeis. Aumenta os Pontos de Movimento máximos em +1 PM permanentemente.' },
    { id: 'atirador_passivo_precisao_mortal', catalogId: '0702000024', name: 'Precisão Mortal', icon: '🎯', class: 'atirador', element: 'none', spellType: 'passive', castType: 'self', targetType: 'none', passiveEffect: { critico: 10 }, description: 'Mira letal. Aumenta a chance de acerto crítico em +10% permanentemente.' },
    { id: 'atirador_passivo_queima_roupa', catalogId: '0702000025', name: 'Tiro à Queima-Roupa', icon: '💥', class: 'atirador', element: 'none', spellType: 'passive', castType: 'self', targetType: 'none', passiveEffect: { closeCombatBonus: { maxRange: 3, damagePercent: 20 } }, description: 'Especialista em combate próximo. +20% de dano causado se o alvo estiver a 3 células ou menos de distância.' },
    { id: 'atirador_passivo_agilidade_felina', catalogId: '0702000026', name: 'Agilidade Felina', icon: '🐱', class: 'atirador', element: 'none', spellType: 'passive', castType: 'self', targetType: 'none', passiveEffect: { dodge: 10 }, description: 'Reflexos felinos. Aumenta a chance de esquiva em +10% permanentemente.' },

    // === DOM (1) ===
    { id: 'atirador_dom_mira_predadora', catalogId: '0702000021', name: 'DOM: Mira Predadora', icon: '🎯', class: 'atirador', element: 'none', spellType: 'dom', domPassive: { trigger: 'onRangedDamage', minRange: 4, pointsPerPA: 5, threshold: 100, critBonus: 20, critDuration: 1, nextHitDmgBonus: 30 }, description: 'Passivo: cada feitiço que causar dano a um alvo a 4+ células ganha 5 pontos por PA gasto. Ao atingir 100 pontos: +20% de crítico por 1 turno e +30% de dano no próximo golpe (não expira até ser consumido). Ao ativar, o contador zera completamente e o feitiço que ativou não acumula mais — use outro feitiço para reacumular.' }
];
