// ========== BANCO DE DADOS: HABILIDADES ATIVAS ==========
// Todos os feitiços ativos do jogo (jogador e monstros).
//
// Campos:
//   spellType  - 'active'
//   castType   - 'targeted' (precisa de alvo) ou 'self' (auto-cast)
//   targetType - 'enemy', 'ally', 'both', 'none'
//   paCost / pmCost / peCost - custos
//   minRange / maxRange - alcance (0-30)
//   rangeShape - 'cross','circle','line','diagonal','star'
//   aoeType    - 'single' (alvo único) ou 'zone' (área)
//   zoneCells  - [{dx,dy},...] offsets da zona (se aoeType='zone')
//   damage     - { min, max, stat } ou null
//   heal       - { min, max, stat } ou null
//   element    - 'fire','water','air','earth'
//   pushPull   - null ou { type:'push'|'pull', distance: N, origin: 'caster'|'zone_center' }
//   passiveEffect - null
//   hotbarSlot - slot na barra (0-9)

const DB_HABILIDADES_ATIVAS = [
    {
        id: 'rajada_arcana',
        catalogId: '0601000001',
        name: 'Rajada Arcana',
        icon: '🔮',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        paCost: 3, pmCost: 0, peCost: 0,
        minRange: 1, maxRange: 2,
        rangeShape: 'circle',
        aoeType: 'single',
        zoneCells: [],
        damage: { min: 8, max: 12, stat: 'strength' },
        element: 'earth',
        pushPull: { type: 'push', distance: 1 },
        passiveEffect: null,
        hotbarSlot: 1
    },
    {
        id: 'bola_de_fogo',
        catalogId: '0601000002',
        name: 'Bola de Fogo',
        icon: '🔥',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        paCost: 4, pmCost: 0, peCost: 0,
        minRange: 1, maxRange: 3,
        rangeShape: 'circle',
        aoeType: 'single',
        zoneCells: [],
        damage: { min: 12, max: 18, stat: 'intelligence' },
        element: 'fire',
        pushPull: null,
        passiveEffect: null,
        hotbarSlot: 2
    },
    {
        id: 'sopro_gelado',
        catalogId: '0601000003',
        name: 'Sopro Gelado',
        icon: '❄️',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        paCost: 3, pmCost: 0, peCost: 1,
        minRange: 1, maxRange: 2,
        rangeShape: 'cross',
        aoeType: 'single',
        zoneCells: [],
        damage: { min: 6, max: 14, stat: 'intelligence' },
        element: 'water',
        pushPull: null,
        passiveEffect: null,
        hotbarSlot: 3
    },
    {
        id: 'rajada_vento',
        catalogId: '0601000004',
        name: 'Rajada de Vento',
        icon: '🌪️',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        paCost: 2, pmCost: 1, peCost: 0,
        minRange: 1, maxRange: 2,
        rangeShape: 'circle',
        aoeType: 'single',
        zoneCells: [],
        damage: { min: 5, max: 10, stat: 'agility' },
        element: 'air',
        pushPull: { type: 'push', distance: 1 },
        passiveEffect: null,
        hotbarSlot: 4
    },
    {
        id: 'tremor',
        catalogId: '0601000005',
        name: 'Tremor',
        icon: '🌍',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        paCost: 4, pmCost: 0, peCost: 2,
        minRange: 1, maxRange: 1,
        rangeShape: 'circle',
        aoeType: 'single',
        zoneCells: [],
        damage: { min: 10, max: 16, stat: 'strength' },
        element: 'earth',
        pushPull: null,
        passiveEffect: null,
        hotbarSlot: 5
    },  
    {
        id: 'intimidar',
        name: 'intimidar',
        icon: '🫸',
        spellType: 'active',
        classTag: '',
        spellCategory: 'player',
        catalogId: '0601000006',
        castType: 'targeted',
        needsTarget: true,
        targetEnemy: true,
        targetAlly: false,
        paCost: 3,
        pmCost: 0,
        peCost: 0,
        minRange: 1,
        maxRange: 8,
        rangeShape: 'star',
        rangeType: 'star',
        requiresLoS: true,
        aoeType: 'single',
        zoneCells: [],
        zoneEffects: {
            dmgCaster: false,
            dmgAlly: false,
            dmgEnemy: true,
            healCaster: false,
            healAlly: false,
            healEnemy: false,
            lifeSteal: false
        },
        pushPull: { type: 'push', distance: 1 },
        element: 'water',
        damage: { min: 5, max: 10, stat: 'luck' },
        heal: null,
        passiveEffect: null,
        cooldown: 0,
        castsPerTurn: 3,
        castsPerTarget: 2,
        initialCooldown: 0
    },
    // Cole dentro do array DB_HABILIDADES_ATIVAS em habilidades/ativas.js:
    {
        id: 'sopro',
        name: 'sopro',
        icon: '🪶',
        spellType: 'active',
        classTag: '',
        spellCategory: 'player',
        catalogId: '0602000001',
        castType: 'targeted',
        needsTarget: false,
        targetEnemy: true,
        targetAlly: true,
        paCost: 2,
        pmCost: 0,
        peCost: 0,
        minRange: 3,
        maxRange: 20,
        rangeShape: 'cross',
        rangeType: 'cross',
        requiresLoS: true,
        aoeType: 'zone',
        zoneMinRadius: 0,
        zoneCells: [
            { dx: -1, dy: 0 },
            { dx: 0, dy: -1 },
            { dx: 0, dy: 1 },
            { dx: 1, dy: 0 }
        ],
        zoneDirectional: false,
        zoneEffects: {
            hitTarget: true,
            dmgCaster: false,
            dmgAlly: false,
            dmgEnemy: true,
            healCaster: false,
            healAlly: false,
            healEnemy: false,
            lifeSteal: false
        },
        pushPull: { type: 'push', distance: 1, origin: 'zone_center' },
        element: 'water',
        damage: { min: 3, max: 6, stat: 'agility' },
        heal: null,
        passiveEffect: null,
        cooldown: 0,
        castsPerTurn: 3,
        castsPerTarget: 2,
        initialCooldown: 0
    },
    {
        id: 'monster_soco_brutal',
        name: 'Soco Brutal',
        icon: '👊',
        description: 'Um golpe poderoso corpo-a-corpo',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 5, max: 10, stat: 'strength' },
        element: 'earth',
        maxRange: 1,
        minRange: 0,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 3,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_investida',
        name: 'Investida',
        icon: '💨',
        description: 'Avança e ataca o inimigo',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 8, max: 12, stat: 'strength' },
        element: 'earth',
        pushPull: { type: 'push', distance: 1 },
        maxRange: 2,
        minRange: 1,
        rangeShape: 'line',
        aoeType: 'single',
        paCost: 4,
        pmCost: 1,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_mordida',
        name: 'Mordida',
        icon: '🦷',
        description: 'Morde o inimigo causando dano',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 4, max: 8, stat: 'luck' },
        element: 'water',
        maxRange: 1,
        minRange: 0,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 3,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_arremesso_pedra',
        name: 'Arremesso de Pedra',
        icon: '🪨',
        description: 'Arremessa uma pedra à distância',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 4, max: 7, stat: 'strength' },
        element: 'earth',
        maxRange: 10,
        minRange: 2,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 3,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_flecha_venenosa',
        name: 'Flecha Venenosa',
        icon: '🏹',
        description: 'Dispara uma flecha com veneno',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 6, max: 10, stat: 'luck' },
        element: 'water',
        maxRange: 5,
        minRange: 2,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 3,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_tiro_preciso',
        name: 'Tiro Preciso',
        icon: '🎯',
        description: 'Um tiro certeiro à distância',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 8, max: 14, stat: 'agility' },
        element: 'air',
        maxRange: 6,
        minRange: 3,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 4,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_rajada_magica',
        name: 'Rajada Mágica',
        icon: '✨',
        description: 'Dispara energia mágica à distância',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 5, max: 9, stat: 'intelligence' },
        element: 'fire',
        maxRange: 4,
        minRange: 2,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 3,
        pmCost: 0,
        peCost: 2,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },

    // === FEITICOS DE BUFF ===
    {
        id: 'furia',
        name: 'Furia',
        icon: '💪',
        spellType: 'active',
        classTag: '',
        spellCategory: 'player',
        catalogId: '0601000007',
        castType: 'targeted',
        needsTarget: false,
        targetEnemy: false,
        targetAlly: false,
        paCost: 2,
        pmCost: 0,
        peCost: 0,
        minRange: 0,
        maxRange: 0,
        rangeShape: 'circle',
        rangeType: 'circle',
        requiresLoS: false,
        aoeType: 'single',
        zoneCells: [],
        zoneEffects: {
            dmgCaster: true,
            dmgAlly: false,
            dmgEnemy: false,
            healCaster: false,
            healAlly: false,
            healEnemy: false,
            lifeSteal: false
        },
        pushPull: null,
        element: 'none',
        damage: null,
        heal: null,
        passiveEffect: null,
        cooldown: 3,
        castsPerTurn: 1,
        castsPerTarget: 1,
        initialCooldown: 0,
        effects: [
            { effectId: 'poderoso', level: 1, target: 'self' }
        ]
    },

    // ===== FEITIÇO DE TESTE COMPLETO (todos os campos preenchidos) =====
    {
        id: 'apenas_teste',
        catalogId: '0699999999',
        name: '@@@@apenas teste@',
        icon: '🌈',
        iconColor: '#ff00ff',
        spellType: 'active',
        castType: 'targeted',
        classTag: 'Guerreiro',
        spellCategory: 'player',
        targetType: 'enemy',
        needsTarget: true,
        targetEnemy: true,
        targetAlly: true,
        minRange: 2,
        maxRange: 8,
        rangeShape: 'circle',
        requiresLoS: true,
        rangeModifiable: true,
        paCost: 5,
        pmCost: 3,
        peCost: 2,
        aoeType: 'zone',
        zoneCells: [{dx:0,dy:0},{dx:1,dy:0},{dx:-1,dy:0},{dx:0,dy:1},{dx:0,dy:-1}],
        zoneEffects: {
            hitTarget: true,
            dmgCaster: true,
            dmgAlly: true,
            dmgEnemy: true,
            healCaster: true,
            healAlly: true,
            healEnemy: false,
            lifeSteal: true
        },
        element: 'fire',
        damage: { min: 25, max: 50, stat: 'intelligence' },
        damages: [
            { min: 25, max: 50, element: 'fire' },
            { min: 10, max: 20, element: 'water' },
            { min: 5, max: 15, element: 'air' }
        ],
        heal: { min: 10, max: 30, stat: 'luck', element: 'water' },
        heals: [
            { min: 10, max: 30 },
            { min: 5, max: 15 }
        ],
        pushPull: { type: 'push', distance: 3, origin: 'caster' },
        armorGrant: { min: 5, max: 10 },
        armorSteal: 3,
        bonusVsArmored: 15,
        cooldown: 3,
        castsPerTurn: 2,
        castsPerTarget: 1,
        initialCooldown: 1,
        effects: [
            { effectId: 'poderoso', level: 2, target: 'self' },
            { effectId: 'cura_amplificada', level: 1, target: 'ally' },
            { effectId: 'cura_reduzida', level: 1, target: 'enemy' },
            { effectId: 'escudo_amplificado', level: 1, target: 'self' },
            { effectId: 'destruidor_escudo', level: 1, target: 'enemy' },
            { effectId: 'roubo_escudo', level: 1, target: 'self' }
        ],
        berserk: 30,
        intacto: 100,
        morteEminente: 15,
        firmeEForte: 50,
        ricochete: { bounces: 3, decayPercent: 25 },
        onKill: { enabled: true, effects: [{ type: 'stealPA', amount: 2 }, { type: 'stealPM', amount: 1 }] },
        description: 'Feitiço de teste com TODOS os campos preenchidos para visualizar no editor de layout.',
        passiveEffect: null,
        hotbarSlot: null
    },

    // === MONSTER SPELLS: MELEE (range 0-1) ===
    {
        id: 'monster_arranhar',
        name: 'Arranhar',
        icon: '🐾',
        description: 'Arranha o inimigo com garras',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 3, max: 6, stat: 'agility' },
        element: 'earth',
        maxRange: 1,
        minRange: 0,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 2,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_mordida_rapida',
        name: 'Mordida Rápida',
        icon: '🐊',
        description: 'Uma mordida veloz e precisa',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 3, max: 5, stat: 'agility' },
        element: 'water',
        maxRange: 1,
        minRange: 0,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 2,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_mordida_venenosa_fraca',
        name: 'Mordida Venenosa Fraca',
        icon: '🐍',
        description: 'Morde injetando veneno fraco',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 4, max: 7, stat: 'strength' },
        element: 'water',
        maxRange: 1,
        minRange: 0,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 3,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_chicote_espinho',
        name: 'Chicote de Espinho',
        icon: '🌿',
        description: 'Golpeia com cipó coberto de espinhos',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 5, max: 8, stat: 'strength' },
        element: 'earth',
        maxRange: 1,
        minRange: 0,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 3,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_espora_toxica',
        name: 'Espora Tóxica',
        icon: '🍄',
        description: 'Libera esporos tóxicos no inimigo',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 3, max: 6, stat: 'intelligence' },
        element: 'water',
        maxRange: 1,
        minRange: 0,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 3,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_mordida_vampirica',
        name: 'Mordida Vampírica',
        icon: '🧛',
        description: 'Morde drenando a vitalidade do inimigo',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 6, max: 10, stat: 'strength' },
        element: 'water',
        maxRange: 1,
        minRange: 0,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 3,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_mordida_venenosa',
        name: 'Mordida Venenosa',
        icon: '☠️',
        description: 'Morde injetando veneno potente',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 7, max: 12, stat: 'strength' },
        element: 'water',
        maxRange: 1,
        minRange: 0,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 3,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_mordida_feroz',
        name: 'Mordida Feroz',
        icon: '🐺',
        description: 'Uma mordida devastadora com força bruta',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 10, max: 16, stat: 'strength' },
        element: 'earth',
        maxRange: 1,
        minRange: 0,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 4,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_mordida_letal',
        name: 'Mordida Letal',
        icon: '🦈',
        description: 'Mordida mortal que dilacera a presa',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 16, max: 24, stat: 'agility' },
        element: 'water',
        maxRange: 1,
        minRange: 0,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 4,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_bote_rapido',
        name: 'Bote Rápido',
        icon: '⚡',
        description: 'Ataque relâmpago que pega o inimigo desprevenido',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 5, max: 9, stat: 'agility' },
        element: 'air',
        maxRange: 1,
        minRange: 0,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 2,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_golpe_ossudo',
        name: 'Golpe Ossudo',
        icon: '🦴',
        description: 'Golpeia com ossos endurecidos',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 8, max: 14, stat: 'strength' },
        element: 'earth',
        maxRange: 1,
        minRange: 0,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 3,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_golpe_furtivo',
        name: 'Golpe Furtivo',
        icon: '🗡️',
        description: 'Ataque silencioso que surpreende o alvo',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 6, max: 12, stat: 'agility' },
        element: 'air',
        maxRange: 1,
        minRange: 0,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 3,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_investida_brutal',
        name: 'Investida Brutal',
        icon: '🦬',
        description: 'Avança com força total empurrando o inimigo',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 12, max: 18, stat: 'strength' },
        element: 'earth',
        pushPull: { type: 'push', distance: 2 },
        maxRange: 2,
        minRange: 1,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 5,
        pmCost: 1,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_coice',
        name: 'Coice',
        icon: '🐴',
        description: 'Coice poderoso que empurra o alvo',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 8, max: 14, stat: 'strength' },
        element: 'earth',
        pushPull: { type: 'push', distance: 1 },
        maxRange: 1,
        minRange: 0,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 3,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_constricao',
        name: 'Constrição',
        icon: '🐙',
        description: 'Agarra e esmaga o inimigo puxando-o para perto',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 10, max: 14, stat: 'strength' },
        element: 'water',
        pushPull: { type: 'pull', distance: 1 },
        maxRange: 4,
        minRange: 2,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 4,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_patada',
        name: 'Patada',
        icon: '🐻',
        description: 'Golpe devastador com pata gigante',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 14, max: 22, stat: 'strength' },
        element: 'earth',
        maxRange: 1,
        minRange: 0,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 4,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_esmagar',
        name: 'Esmagar',
        icon: '🔨',
        description: 'Esmaga o inimigo com força colossal',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 18, max: 28, stat: 'strength' },
        element: 'earth',
        maxRange: 1,
        minRange: 0,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 5,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_porretada',
        name: 'Porretada',
        icon: '🪵',
        description: 'Golpe pesado com porrete que empurra o alvo',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 16, max: 26, stat: 'strength' },
        element: 'earth',
        pushPull: { type: 'push', distance: 1 },
        maxRange: 1,
        minRange: 0,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 4,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_soco_rochoso',
        name: 'Soco Rochoso',
        icon: '🪨',
        description: 'Soco com punhos de pedra',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 15, max: 24, stat: 'strength' },
        element: 'earth',
        maxRange: 1,
        minRange: 0,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 4,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_golpe_cauda',
        name: 'Golpe de Cauda',
        icon: '🦎',
        description: 'Chicoteia o inimigo com a cauda empurrando-o',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 12, max: 20, stat: 'strength' },
        element: 'earth',
        pushPull: { type: 'push', distance: 1 },
        maxRange: 1,
        minRange: 0,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 3,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_garras_vento',
        name: 'Garras de Vento',
        icon: '💨',
        description: 'Corta o ar com garras velozes',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 12, max: 18, stat: 'agility' },
        element: 'air',
        maxRange: 1,
        minRange: 0,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 3,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },

    // === MONSTER SPELLS: SEMI-RANGE (1-2) ===
    {
        id: 'monster_lingua_chicote',
        name: 'Língua Chicote',
        icon: '🐸',
        description: 'Ataca com a língua como um chicote',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 3, max: 6, stat: 'agility' },
        element: 'water',
        maxRange: 2,
        minRange: 1,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 2,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_salto_esmagador',
        name: 'Salto Esmagador',
        icon: '🦘',
        description: 'Salta sobre o inimigo esmagando-o',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 6, max: 10, stat: 'strength' },
        element: 'earth',
        pushPull: { type: 'push', distance: 1 },
        maxRange: 2,
        minRange: 1,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 4,
        pmCost: 1,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_teia_pegajosa',
        name: 'Teia Pegajosa',
        icon: '🕸️',
        description: 'Lança teia que prende o inimigo por 1 turno',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 2, max: 4, stat: 'agility' },
        element: 'water',
        maxRange: 2,
        minRange: 1,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 3,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true,
        advancedStatus: [{ type: 'preso', duration: 1 }],
        cooldown: 2,
        castsPerTurn: 1
    },
    {
        id: 'monster_raiz_prendedora',
        name: 'Raiz Prendedora',
        icon: '🌱',
        description: 'Raízes brotam do chão prendendo o inimigo por 1 turno',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 3, max: 5, stat: 'strength' },
        element: 'earth',
        maxRange: 2,
        minRange: 1,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 3,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true,
        advancedStatus: [{ type: 'preso', duration: 1 }],
        cooldown: 2,
        castsPerTurn: 1
    },

    // === MONSTER SPELLS: RANGED (2+) ===
    {
        id: 'monster_nuvem_esporos',
        name: 'Nuvem de Esporos',
        icon: '🍄',
        description: 'Libera uma nuvem de esporos tóxicos à distância',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 4, max: 7, stat: 'intelligence' },
        element: 'water',
        maxRange: 3,
        minRange: 1,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 3,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_cuspe_venenoso',
        name: 'Cuspe Venenoso',
        icon: '🤮',
        description: 'Cospe veneno ácido à distância',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 8, max: 12, stat: 'intelligence' },
        element: 'water',
        maxRange: 4,
        minRange: 2,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 3,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_arremesso_osso',
        name: 'Arremesso de Osso',
        icon: '🦴',
        description: 'Arremessa um osso afiado no inimigo',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 7, max: 11, stat: 'strength' },
        element: 'earth',
        maxRange: 4,
        minRange: 2,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 3,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_grito_sonico',
        name: 'Grito Sônico',
        icon: '🔊',
        description: 'Emite um grito ensurdecedor que causa dano',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 5, max: 8, stat: 'agility' },
        element: 'air',
        maxRange: 3,
        minRange: 1,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 3,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_arremesso_rocha',
        name: 'Arremesso de Rocha',
        icon: '🏔️',
        description: 'Arremessa uma rocha enorme no inimigo',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 12, max: 18, stat: 'strength' },
        element: 'earth',
        maxRange: 5,
        minRange: 2,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 4,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_rajada_cristal',
        name: 'Rajada de Cristal',
        icon: '💎',
        description: 'Dispara fragmentos de cristal cortantes',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 14, max: 22, stat: 'intelligence' },
        element: 'earth',
        maxRange: 4,
        minRange: 2,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 4,
        pmCost: 0,
        peCost: 2,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_grito_sonico_forte',
        name: 'Grito Sônico Forte',
        icon: '📢',
        description: 'Grito devastador que abala o inimigo',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 10, max: 16, stat: 'agility' },
        element: 'air',
        maxRange: 3,
        minRange: 1,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 3,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_rajada_ar',
        name: 'Rajada de Ar',
        icon: '🌬️',
        description: 'Dispara uma corrente de ar cortante',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 10, max: 15, stat: 'agility' },
        element: 'air',
        maxRange: 4,
        minRange: 2,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 3,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_rajada_magica_forte',
        name: 'Rajada Mágica Forte',
        icon: '🌟',
        description: 'Dispara uma poderosa rajada de energia mágica',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 12, max: 20, stat: 'intelligence' },
        element: 'fire',
        maxRange: 4,
        minRange: 2,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 4,
        pmCost: 0,
        peCost: 2,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },
    {
        id: 'monster_cuspe_acido',
        name: 'Cuspe Ácido',
        icon: '🧪',
        description: 'Cospe ácido corrosivo que queima o inimigo',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'enemy',
        damage: { min: 10, max: 16, stat: 'intelligence' },
        element: 'water',
        maxRange: 4,
        minRange: 2,
        rangeShape: 'cross',
        aoeType: 'single',
        paCost: 3,
        pmCost: 0,
        peCost: 0,
        targetEnemy: true,
        targetAlly: false,
        requiresLoS: true
    },

    // === MONSTER SPELLS: BUFFS ===
    {
        id: 'monster_uivo',
        name: 'Uivo',
        icon: '🐺',
        description: 'Uiva para aumentar a força temporariamente (+10% dano por 2 turnos)',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'none',
        damage: null,
        element: 'none',
        maxRange: 0,
        minRange: 0,
        rangeShape: 'circle',
        aoeType: 'single',
        paCost: 2,
        pmCost: 0,
        peCost: 0,
        targetEnemy: false,
        targetAlly: false,
        requiresLoS: false,
        effects: [{ effectId: 'poderoso', level: 1, target: 'self' }],
        cooldown: 3,
        castsPerTurn: 1
    },
    {
        id: 'monster_rugido',
        name: 'Rugido',
        icon: '🦁',
        description: 'Ruge ferozmente e se protege (ganha 8 de escudo)',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'none',
        damage: null,
        element: 'none',
        maxRange: 0,
        minRange: 0,
        rangeShape: 'circle',
        aoeType: 'single',
        paCost: 2,
        pmCost: 0,
        peCost: 0,
        targetEnemy: false,
        targetAlly: false,
        requiresLoS: false,
        armorGrant: { min: 6, max: 10 },
        cooldown: 3,
        castsPerTurn: 1
    },
    {
        id: 'monster_carapaca',
        name: 'Carapaça',
        icon: '🐢',
        description: 'Endurece a carapaça (ganha 10 de escudo)',
        spellType: 'active',
        castType: 'targeted',
        targetType: 'none',
        damage: null,
        element: 'none',
        maxRange: 0,
        minRange: 0,
        rangeShape: 'circle',
        aoeType: 'single',
        paCost: 2,
        pmCost: 0,
        peCost: 0,
        targetEnemy: false,
        targetAlly: false,
        requiresLoS: false,
        armorGrant: { min: 8, max: 14 },
        cooldown: 3,
        castsPerTurn: 1
    },

    // Cole o proximo item aqui

];
